config/routes.rb
Newsportal::Application.routes.draw do
  resources :news
  root :to => 'news#index', as: 'home'

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :category, :title, :description, :image_url
  validates :category, :title, :description, :image_url, :presence=>{message: ': Please fill in all fields'}
  validates :title, :uniqueness => {message: ' : must be uniqueness'}
  validates :image_url, :allow_blank=> true, format: {
      with: %r{\.(gif|jpg|png)$}i,
      message: ' : must be a URL with gif, jpg or png image'
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gamz news</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class= '<%=controller.controller_name%>'>

<%= yield %>

</body>
</html>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
        <div id="error_explanation" xmlns="http://www.w3.org/1999/html">
      <h2><%= pluralize(@news.errors.count, "error") %> </h2>

      <ul>
      <h3 id="error" style="color:orangered">
      <% @news.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
      <% end %>
      </h3>
      </ul>
    </div>
  <% end %>

  <div class="field">
        <%= f.label :category %><br />
        <%= f.text_field :category %>
  </div>
  <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
  </div>
  <div class="field">
        <%= f.label :description %> <br />
        <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
        <%= f.label :image_url %> <br />
        <%= f.file_field :image_url %>
  </div>
  <div class="actions">
    <br></br>
        <%= f.submit %>
    <br></br>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<table>

<% @news.each do |news| %>
  <tr class= "<%=cycle('list_line_odd','list_line_even')%>">
    <td>
      <%=image_tag(news.image_url,class: 'list_image') %>
    </td>
    <td class= "list_category">
     <p style= "color: white"> <%= news.category %> </p>
    </td>
    <td class= "list_description">
      <dl>
        <dt><%= news.title %></dt>
        <dd><%= truncate(strip_tags(news.description),length: 80) %></dd>
      </dl>
    </td>
    <td class= "list_actions">
        <p><%= link_to 'Show', news %></p>
        <p><%= link_to 'Edit', edit_news_path(news) %></p>
        <p><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add     News', new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<table>

  <td>
    <%=image_tag(@news.image_url,class: 'list_image') %>
  </td>
  <td class= "list_category">
    <p style= "color: white"> <%= @news.category %> </p>
  </td>
  <td class= "one_news">
    <dl>
      <dt><%= @news.title %></dt>
      <dd><%= @news.description %></dd>
    </dl>
  </td>

  <%= link_to 'Edit', edit_news_path(@news) %> |
  <%= link_to 'Back', news_index_path %>

</table>